name: Build MacOS executable

on: 
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'
          spec: 'GUI_mac.spec'
          # requirements: 'src/requirements.txt'
          upload_exe_with_name: 'GUI'
          options: --onefile, --windowed,
